name: QualWeb Accessibility Scan_try2
# QualWeb (University of Lisbon) - Focus on W3C ACT Rules
on:
  push:
    branches:
      - "feature/**"
      - "main"
  workflow_dispatch:

jobs:
  qualweb-scan:
    runs-on: ubuntu-latest
    steps:
      # 1. Setup
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # 2. Install Dependencies
      - name: Install Dependencies
        run: |
            npm ci
            npm install wait-on

      # 3. Build Project
      - name: Build Project
        run: npm run build --if-present

      # 4. Start Server
      - name: Start Server
        run: |
            npm start &
            npx wait-on http://localhost:1338

      # 5. Execute QualWeb Scan
      - name: Run QualWeb Script
        run: node qualweb-scan.js http://localhost:1338/

      # 6. Testing
      - name: Check for Violations
        run: |
          # Scanning for "outcome":"failed" in file?
          if grep -q '"outcome":"failed"' report.json; then
            echo "::error::Accessibility Violations Found!"
            # Count Occurrences
            COUNT=$(grep -o '"outcome":"failed"' report.json | wc -l)
            echo "Total failed rules: $COUNT"
            exit 1
          else
            echo "::notice::No Accessibility Violations Found."
          fi

      # 7. Upload Results
      - name: Generate Analysis Report
        run: |
          # making sure results directory exists
            mkdir -p results
          
          # generate_report.js requires an file
            echo '{"summary": {}, "report": []}' > results/report.json
                                                      
          # 3. starting the script to generate a report
            node generate_report.js qualweb report.json

      - name: Upload Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: qualweb-report
          path: |
            report.json
            results/report.json