name: QualWeb Accessibility Scan

on:
  workflow_dispatch:
  push:
    branches: ['**']

env:
  TEST_URL: http://127.0.0.1:1338
  PORT: 1338

jobs:
  qualweb-scan:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        view:
          - "" # index.html
          - "perceivable.html"
          - "operable.html"
          - "understandable.html"
          - "robust.html"
          - "dictionary.html"

    steps:
      # 1. Checkout
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Setup Node 20
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. Install Dependencies
      - name: Install Dependencies
        run: npm install

      # 4. Build
      - name: Build Project
        run: npm run build --if-present

      # 5. Start Server
      - name: Start Server
        run: |
          export NODE_OPTIONS="--dns-result-order=ipv4first"
          npm start &
          echo "Waiting for server..."
          npx wait-on --timeout 60000 $TEST_URL

      # 6. Run QualWeb
      - name: Run QualWeb on ${{ matrix.view }}
        continue-on-error: true
        env:
          TARGET_URL: ${{ env.TEST_URL }}/${{ matrix.view }}
        run: |
              node run_scan.js

      # 7. Upload Results
      - name: Upload QualWeb Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: qualweb-json-results-${{ strategy.job-index }}
          path: qualweb-results/*.json